import { AppLanguage } from "./i18n";

type HelpText = Record<AppLanguage, string>;
export type HelpSection = { id: string; title: HelpText; body: HelpText };

const item = (id: string, enTitle: string, enBody: string, hinglishTitle: string, hinglishBody: string, hiTitle: string, hiBody: string): HelpSection => ({
  id,
  title: { en: enTitle, hinglish: hinglishTitle, hi: hiTitle },
  body: { en: enBody, hinglish: hinglishBody, hi: hiBody },
});

export const helpAvailabilityNotice: HelpText = {
  en: "This guide describes Legal Saathi's configured experience. What you can use now depends on your account, active plan, provider, and environment; check the visible state before relying on a feature.",
  hinglish: "Yeh guide Legal Saathi ke configured experience ko explain karta hai. Aap abhi kya use kar sakte hain, woh account, active plan, provider aur environment par depend karta hai; kisi feature par rely karne se pehle visible state check karein.",
  hi: "यह गाइड Legal Saathi के कॉन्फ़िगर अनुभव को समझाती है। आप अभी क्या उपयोग कर सकते हैं, यह आपके खाते, सक्रिय प्लान, प्रदाता और वातावरण पर निर्भर करता है; किसी सुविधा पर भरोसा करने से पहले उसकी दिखाई गई स्थिति जाँचें।",
};

export const helpSections: HelpSection[] = [
  item("getting-started", "Getting started", "Sign in, accept the safety notice, then ask a legal-preparation question or create a case.", "Shuru kaise karein", "Sign in karein, safety notice accept karein, phir legal-preparation sawaal poochhein ya case banayein.", "शुरुआत कैसे करें", "साइन इन करें, सुरक्षा सूचना स्वीकार करें, फिर कानूनी तैयारी का प्रश्न पूछें या केस बनाएँ।"),
  item("google-sign-in", "Google sign-in", "Google verifies your identity; Legal Saathi never asks for your Google password.", "Google sign-in", "Google aapki identity verify karta hai; Legal Saathi aapka Google password kabhi nahi maangta.", "गूगल साइन-इन", "गूगल आपकी पहचान सत्यापित करता है; लीगल साथी आपका गूगल पासवर्ड कभी नहीं माँगता।"),
  item("session-security", "Session security", "Legal Saathi uses a verified HttpOnly app session with expiry, rotation, CSRF protection, and logout controls.", "Session security", "Legal Saathi verified HttpOnly app session, expiry, rotation, CSRF protection aur logout controls use karta hai.", "सत्र सुरक्षा", "Legal Saathi सत्यापित HttpOnly ऐप सत्र, समय-सीमा, रोटेशन, CSRF सुरक्षा और लॉगआउट नियंत्रण का उपयोग करता है।"),
  item("consent", "Terms and safety consent", "Consent is required before AI or document questions and is stored with a version and timestamp.", "Terms aur safety consent", "AI ya document sawaal se pehle consent zaroori hai; version aur time backend par save hote hain.", "शर्तें और सुरक्षा सहमति", "एआई या दस्तावेज़ प्रश्न से पहले सहमति आवश्यक है; संस्करण और समय बैकएंड पर सुरक्षित होते हैं।"),
  item("ai-chat", "AI legal preparation chat", "Use chat for general legal information, fact organization, and questions to discuss with an advocate.", "AI legal preparation chat", "Chat ko general legal information, facts organize karne aur advocate se poochhne wale sawaalon ke liye use karein.", "एआई कानूनी तैयारी चैट", "चैट का उपयोग सामान्य कानूनी जानकारी, तथ्य व्यवस्थित करने और अधिवक्ता से पूछने वाले प्रश्नों के लिए करें।"),
  item("languages", "Languages", "Choose English, Hinglish, or Hindi; an explicit language request in your message may override the preference.", "Languages", "English, Hinglish ya Hindi choose karein; message mein clear language request preference ko override kar sakti hai.", "भाषाएँ", "अंग्रेज़ी, हिंग्लिश या हिंदी चुनें; संदेश में स्पष्ट भाषा अनुरोध प्राथमिकता को बदल सकता है।"),
  item("models", "Model choices", "Only models configured by the operator and allowed by your plan can be selected.", "Model choices", "Sirf configured aur aapke plan mein allowed models select ho sakte hain.", "मॉडल विकल्प", "केवल ऑपरेटर द्वारा कॉन्फ़िगर और आपकी योजना में अनुमत मॉडल चुने जा सकते हैं।"),
  item("auto", "Auto model", "Auto selects an entitled configured class based on request size, context, and Web use; it never silently selects Ultra.", "Auto model", "Auto request size, context aur Web ke hisaab se allowed model choose karta hai; Ultra kabhi silently select nahi hota.", "ऑटो मॉडल", "ऑटो अनुरोध आकार, संदर्भ और वेब उपयोग के अनुसार अनुमत मॉडल चुनता है; यह चुपचाप अल्ट्रा नहीं चुनता।"),
  item("fast", "Fast model", "Fast is concise, uses one base unit, and has no speed multiplier.", "Fast model", "Fast concise hai, ek base unit use karta hai aur speed multiplier nahi deta.", "फास्ट मॉडल", "फास्ट संक्षिप्त है, एक मूल यूनिट उपयोग करता है और इसमें गति गुणक नहीं है।"),
  item("flash", "Flash model", "Flash balances speed and reasoning and uses two base units.", "Flash model", "Flash speed aur reasoning balance karta hai aur do base units use karta hai.", "फ्लैश मॉडल", "फ्लैश गति और तर्क का संतुलन करता है और दो मूल यूनिट उपयोग करता है।"),
  item("pro", "Pro model", "Pro needs Plus or higher, uses six base units, and has a rolling message window.", "Pro model", "Pro ke liye Plus ya higher plan chahiye, chhe base units lagte hain aur rolling message limit hoti hai.", "प्रो मॉडल", "प्रो के लिए प्लस या उच्च योजना चाहिए, छह मूल यूनिट लगते हैं और रोलिंग संदेश सीमा होती है।"),
  item("ultra", "Ultra model", "Ultra needs Pro or Max, uses fifteen base units, and is never selected automatically.", "Ultra model", "Ultra ke liye Pro ya Max chahiye, pandrah base units lagte hain aur yeh automatically select nahi hota.", "अल्ट्रा मॉडल", "अल्ट्रा के लिए प्रो या मैक्स चाहिए, पंद्रह मूल यूनिट लगते हैं और यह अपने आप नहीं चुना जाता।"),
  item("thinking", "Standard and Extended thinking", "Extended thinking is available only for configured Pro or Ultra models and doubles the model-unit multiplier.", "Standard aur Extended thinking", "Extended sirf configured Pro ya Ultra par milta hai aur model-unit multiplier double karta hai.", "स्टैंडर्ड और एक्सटेंडेड थिंकिंग", "एक्सटेंडेड केवल कॉन्फ़िगर प्रो या अल्ट्रा पर मिलता है और मॉडल यूनिट गुणक दोगुना करता है।"),
  item("speed", "Speed controls", "1.5x and 2x prioritize provider throughput and reduce output budgets; availability depends on the model contract.", "Speed controls", "1.5x aur 2x provider throughput ko priority dete hain aur output budget ghata sakte hain; availability model par depend karti hai.", "गति नियंत्रण", "1.5x और 2x प्रदाता थ्रूपुट को प्राथमिकता देते हैं और आउटपुट सीमा घटा सकते हैं; उपलब्धता मॉडल पर निर्भर है।"),
  item("units", "How units are calculated", "Units combine model, thinking, speed, Web, and bounded document-context costs; the backend calculates the final charge.", "Units kaise calculate hote hain", "Model, thinking, speed, Web aur bounded document context milkar units bante hain; final charge backend calculate karta hai.", "यूनिट कैसे गिने जाते हैं", "मॉडल, थिंकिंग, गति, वेब और सीमित दस्तावेज़ संदर्भ मिलकर यूनिट बनाते हैं; अंतिम शुल्क बैकएंड तय करता है।"),
  item("included-units", "Included units", "Included units reset on the backend-defined 30-day plan cycle and are consumed before purchased units.", "Included units", "Included units backend ke 30-day plan cycle par reset hote hain aur purchased units se pehle use hote hain.", "शामिल यूनिट", "शामिल यूनिट बैकएंड की 30-दिन योजना अवधि पर रीसेट होते हैं और खरीदे गए यूनिट से पहले उपयोग होते हैं।"),
  item("topups", "Top-up units", "Top-ups are controlled Test Mode packages awaiting commercial approval and never grant from frontend state alone.", "Top-up units", "Top-ups controlled Test Mode packages hain, commercial approval pending hai, aur frontend state se kabhi grant nahi hote.", "टॉप-अप यूनिट", "टॉप-अप नियंत्रित टेस्ट मोड पैकेज हैं, व्यावसायिक स्वीकृति लंबित है, और केवल फ्रंटएंड स्थिति से कभी नहीं मिलते।"),
  item("quotas", "Rolling quotas", "Pro and Ultra also have time-window message limits shown beside the model controls.", "Rolling quotas", "Pro aur Ultra ke time-window message limits bhi hote hain, jo model controls ke paas dikhte hain.", "रोलिंग कोटा", "प्रो और अल्ट्रा की समय-सीमा संदेश सीमाएँ भी होती हैं, जो मॉडल नियंत्रण के पास दिखती हैं।"),
item("web-search", "Web search", "Web uses each plan's backend allowance and runs only when a configured search provider succeeds. Free includes 10 manual searches per 30 days, Plus includes 20 per 7 days, and Pro includes 50 per 7 days.", "Web search", "Web har plan ki backend allowance use karta hai aur configured search provider successful hone par hi chalta hai. Free mein har 30 din mein 10, Plus mein har 7 din mein 20, aur Pro mein har 7 din mein 50 manual searches milte hain.", "वेब खोज", "वेब हर योजना की बैकएंड सीमा के अनुसार चलता है और कॉन्फ़िगर किया गया खोज प्रदाता सफल होने पर ही उपयोग होता है। Free में हर 30 दिन में 10, Plus में हर 7 दिन में 20 और Pro में हर 7 दिन में 50 मैनुअल खोज शामिल हैं।"),
  item("citations", "Sources and citations", "Web results prefer official sources, show URLs, and must still be checked for current law and procedure.", "Sources aur citations", "Web results official sources ko prefer karte hain, URLs dikhate hain, phir bhi current law ke liye verify karein.", "स्रोत और उद्धरण", "वेब परिणाम आधिकारिक स्रोतों को प्राथमिकता देते हैं, यूआरएल दिखाते हैं, फिर भी वर्तमान कानून के लिए जाँचें।"),
  item("case-folder", "Case folder", "Case folders keep owner-scoped summaries and preparation outputs on the backend.", "Case folder", "Case folders owner-scoped summaries aur preparation outputs backend par rakhte hain.", "केस फ़ोल्डर", "केस फ़ोल्डर मालिक-सीमित सारांश और तैयारी परिणाम बैकएंड पर रखते हैं।"),
  item("create-case", "Create a case", "Create a case from a truthful story or a completed chat; plan limits are enforced server-side.", "Case banayein", "Sachchi story ya completed chat se case banayein; plan limits backend enforce karta hai.", "केस बनाएँ", "सत्य कहानी या पूरी चैट से केस बनाएँ; योजना सीमाएँ बैकएंड लागू करता है।"),
  item("case-memory", "Case memory", "Saved case memory is reopened for the same verified owner and is not shared across users.", "Case memory", "Saved case memory sirf verified owner ke liye reopen hoti hai, doosre users se share nahi hoti.", "केस मेमोरी", "सहेजी केस मेमोरी केवल सत्यापित मालिक के लिए खुलती है और अन्य उपयोगकर्ताओं से साझा नहीं होती।"),
  item("uploads", "Document uploads", "Development accepts bounded PDF, PNG, JPEG, and text fixtures; production uploads stay disabled until malware controls exist.", "Document uploads", "Development mein bounded PDF, PNG, JPEG aur text fixtures allowed hain; malware controls ke bina production uploads band rahenge.", "दस्तावेज़ अपलोड", "विकास में सीमित पीडीएफ, पीएनजी, जेपीईजी और टेक्स्ट नमूने स्वीकार हैं; मालवेयर नियंत्रण से पहले प्रोडक्शन अपलोड बंद रहेंगे।"),
  item("ocr", "OCR and extraction", "The app shows whether text extraction or OCR actually ran and never pretends an unread file was analyzed.", "OCR aur extraction", "App clearly dikhata hai ki extraction ya OCR hua ya nahi; unread file ko analyzed nahi batata.", "ओसीआर और निष्कर्षण", "ऐप स्पष्ट दिखाता है कि निष्कर्षण या ओसीआर हुआ या नहीं; अपठित फ़ाइल को विश्लेषित नहीं बताता।"),
  item("document-questions", "Document questions", "Questions use only owned extracted content and should show file or page references when available.", "Document questions", "Sawaal sirf owned extracted content use karte hain aur available ho to file ya page reference dikhate hain.", "दस्तावेज़ प्रश्न", "प्रश्न केवल मालिक के निकाले गए पाठ का उपयोग करते हैं और उपलब्ध होने पर फ़ाइल या पृष्ठ संदर्भ दिखाते हैं।"),
  item("delete-document", "Delete a document", "Document deletion requires confirmation and ownership; deleted assets become inaccessible.", "Document delete karein", "Document deletion ke liye confirmation aur ownership chahiye; deleted asset inaccessible ho jata hai.", "दस्तावेज़ हटाएँ", "दस्तावेज़ हटाने के लिए पुष्टि और स्वामित्व चाहिए; हटाई संपत्ति पहुँच से बाहर हो जाती है।"),
  item("case-trash", "Delete and restore cases", "Case deletion moves the case to trash first; restore availability follows the configured retention period.", "Case delete aur restore", "Case pehle trash mein jata hai; restore configured retention period tak milta hai.", "केस हटाना और पुनर्स्थापित करना", "केस पहले ट्रैश में जाता है; पुनर्स्थापना कॉन्फ़िगर अवधि तक उपलब्ध रहती है।"),
  item("preparation", "Case preparation outputs", "Summaries, facts, timelines, gaps, questions, risks, and next steps are AI-assisted drafts for review.", "Case preparation outputs", "Summary, facts, timeline, gaps, questions, risks aur next steps AI-assisted drafts hain; review zaroor karein.", "केस तैयारी परिणाम", "सारांश, तथ्य, समयरेखा, कमियाँ, प्रश्न, जोखिम और अगले कदम एआई-सहायित प्रारूप हैं; समीक्षा करें।"),
  item("export-notes", "Export and briefs", "Exports must include the generation date and legal disclaimer; review them before sharing with an advocate.", "Export aur briefs", "Exports mein generation date aur disclaimer hona chahiye; advocate ko bhejne se pehle review karein.", "निर्यात और ब्रीफ़", "निर्यात में निर्माण तिथि और कानूनी अस्वीकरण होना चाहिए; अधिवक्ता से साझा करने से पहले समीक्षा करें।"),
  item("plans", "Plans", "Free is INR 0, Plus INR 499 per 30 days, Pro INR 999 per 30 days, and Max is admin-only.", "Plans", "Free INR 0, Plus INR 499/30 days, Pro INR 999/30 days hai; Max admin-only hai.", "योजनाएँ", "फ्री 0 रुपये, प्लस 499 रुपये प्रति 30 दिन, प्रो 999 रुपये प्रति 30 दिन है; मैक्स केवल एडमिन के लिए है।"),
  item("coupons", "Coupons", "Coupons are validated and reserved by the backend and are checked again during order creation.", "Coupons", "Coupons backend validate aur reserve karta hai, aur order banate waqt dobara check hote hain.", "कूपन", "कूपन बैकएंड द्वारा सत्यापित और आरक्षित होते हैं तथा ऑर्डर बनाते समय फिर जाँचे जाते हैं।"),
  item("payments", "Razorpay payments", "Pricing, currency, ownership, and signatures are verified on the backend; checkout clicks never grant a plan.", "Razorpay payments", "Price, currency, ownership aur signature backend verify karta hai; checkout click se plan grant nahi hota.", "रेज़रपे भुगतान", "कीमत, मुद्रा, स्वामित्व और हस्ताक्षर बैकएंड जाँचता है; चेकआउट क्लिक से योजना नहीं मिलती।"),
  item("payment-cancel", "Cancelled payments", "Closing or failing checkout does not upgrade the account or consume a coupon permanently.", "Cancelled payments", "Checkout close ya fail hone par account upgrade nahi hota aur coupon permanently consume nahi hota.", "रद्द भुगतान", "चेकआउट बंद या विफल होने पर खाता अपग्रेड नहीं होता और कूपन स्थायी रूप से खर्च नहीं होता।"),
  item("refunds", "Refunds and disputes", "Refunds and disputes are recorded for admin reconciliation and never create a negative unit balance.", "Refunds aur disputes", "Refund/dispute admin reconciliation ke liye record hote hain aur negative unit balance nahi banate.", "रिफंड और विवाद", "रिफंड और विवाद एडमिन मिलान के लिए दर्ज होते हैं और ऋणात्मक यूनिट शेष नहीं बनाते।"),
  item("admin", "Admin controls", "Admin actions require backend authorization and are audited; normal users cannot grant plans or reset usage.", "Admin controls", "Admin actions backend authorization aur audit maangte hain; normal user plan grant ya usage reset nahi kar sakta.", "एडमिन नियंत्रण", "एडमिन कार्यों के लिए बैकएंड अनुमति और ऑडिट चाहिए; सामान्य उपयोगकर्ता योजना या उपयोग रीसेट नहीं कर सकता।"),
  item("privacy", "Privacy basics", "Legal Saathi minimizes data sent to approved providers and redacts supported personal identifiers in Safe Mode.", "Privacy basics", "Legal Saathi approved providers ko minimum data bhejta hai aur Safe Mode mein supported personal identifiers redact karta hai.", "गोपनीयता मूल बातें", "लीगल साथी स्वीकृत प्रदाताओं को न्यूनतम डेटा भेजता है और सेफ मोड में समर्थित निजी पहचान छिपाता है।"),
  item("sensitive-data", "Do not enter sensitive data", "Do not enter Aadhaar, PAN, bank details, passwords, full addresses, sealed records, or unnecessary private documents.", "Sensitive data mat daalein", "Aadhaar, PAN, bank details, passwords, full address, sealed records ya unnecessary private documents mat daalein.", "संवेदनशील डेटा न डालें", "आधार, पैन, बैंक विवरण, पासवर्ड, पूरा पता, सीलबंद रिकॉर्ड या अनावश्यक निजी दस्तावेज़ न डालें।"),
  item("urgent-matters", "Urgent or criminal matters", "For arrest, bail, violence, police, court deadlines, or serious criminal matters, consult a licensed advocate immediately.", "Urgent ya criminal matters", "Arrest, bail, violence, police, court deadline ya serious criminal matter mein licensed advocate se turant baat karein.", "तात्कालिक या आपराधिक मामले", "गिरफ्तारी, जमानत, हिंसा, पुलिस, अदालत की समय-सीमा या गंभीर आपराधिक मामले में तुरंत लाइसेंस प्राप्त अधिवक्ता से बात करें।"),
  item("accuracy", "Accuracy and current law", "AI can be wrong or outdated; verify important points with official sources and a qualified advocate.", "Accuracy aur current law", "AI galat ya outdated ho sakta hai; important points official sources aur qualified advocate se verify karein.", "सटीकता और वर्तमान कानून", "एआई गलत या पुराना हो सकता है; महत्वपूर्ण बिंदु आधिकारिक स्रोत और योग्य अधिवक्ता से सत्यापित करें।"),
  item("data-rights", "Export and deletion requests", "Authenticated export is owner-scoped; deletion creates a verified pending request because some payment records may require retention.", "Export aur deletion requests", "Authenticated export owner-scoped hai; deletion verified pending request banata hai kyunki kuch payment records retain karne pad sakte hain.", "निर्यात और हटाने के अनुरोध", "सत्यापित निर्यात मालिक तक सीमित है; हटाने का अनुरोध लंबित बनता है क्योंकि कुछ भुगतान रिकॉर्ड रखना आवश्यक हो सकता है।"),
  item("support", "Support", "Email inceptionaistudios@gmail.com without sending passwords, payment secrets, or private legal documents.", "Support", "inceptionaistudios@gmail.com par email karein; password, payment secret ya private legal documents mat bhejein.", "सहायता", "inceptionaistudios@gmail.com पर ईमेल करें; पासवर्ड, भुगतान रहस्य या निजी कानूनी दस्तावेज़ न भेजें।"),
];

if (helpSections.length !== 42) throw new Error("Help content must contain exactly 42 sections.");
